language: python
python:
    - "3.5.2"
    - "3.6"
services: postgresql
env:
    - DJANGO=1.10.5
install:
    - pip insall -q Django==$DJANGO --use-mirrors
    - pip install pep8 --use-mirrors
    - pip install psycopg2 --use-mirrors
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    - cp .env.travis .env
script:
    - python manage.py test
