language: python
python:
    - "3.5.2"
    - "3.6"
services: postgresql
env:
    - DJANGO=1.10.5
install:
    - pip install -q Django==$DJANGO
    - pip install -r requirements.txt
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    - cp .env.travis .env
script:
    - python manage.py test
