language: python
python:
- 3.5.2
- '3.6'
services: postgresql
env:
- DJANGO=1.10.5
install:
- pip install -q Django==$DJANGO
- pip install -r requirements.txt
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp .env.travis .env
- echo -e "Host dev.mbell.me\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
- python manage.py test
before_install:
- openssl aes-256-cbc -K $encrypted_37370079a538_key -iv $encrypted_37370079a538_iv
  -in travis.pem.enc -out travis.pem -d
deploy:
    provider: script
    script: deploy.sh
    skip_cleanup: true
    on:
      branch: master
